[package]
name = "fetris_server"
version = "0.2.0"
description="A reimplementation of Tetris in Rust. Server side."
authors = ["Lancelot Owczarczak <contact@lancelot.life>"]
edition = "2018"

[dependencies]
fetris_protocol = { path = "../protocol" }
rand = "0.7.2"
clap = "2.33.0"
